export const Questions = [
  {
    prompt: "HTML-hujjatda mijoz tomonidan ishlaydigan skriptlarni ulashga imkon beruvchi tegni ko'rsating.",
    optionA: "<applet>",
    optionB: "<script>",
    optionC: "<object>",
    optionD: "<client>",
    answer: "optionB",
  },
  {
    prompt: "HTML hujjatida <title>, <link> va <meta> teglari qaysi bo'limda belgilanishi kerak.",
    optionA: "<body> bo'limida",
    optionB: "Ushbu teglar hujjatning istalgan joyida aniqlanishi mumkin",
    optionC: "<footer>",
    optionD: "<head> qismida",
    answer: "optionD",
  },
  {
    prompt: " Yangi brauzer yorlig'ida / oynasida havolani qanday ochish mumkin?",
    optionA: "<a href=<url< target=<new<>",
    optionB: "<a href=<url< target=<_blank<>",
    optionC: "<a href=<url< new>",
    optionD: "bilmayman",
    answer: "optionB",
  },
  {
    prompt: "Belgilangan ro'yxatni qanday tuzish mumkin?",
    optionA: "<dl>",
    optionB: "<ol>",
    optionC: "<list>",
    optionD: "<ul>",
    answer: "optionD",
  },
  {
    prompt: "Matnning ahamiyatini belgilaydigan tegni tanlang",
    optionA: "<strong>",
    optionB: "<b>",
    optionC: "<important>",
    optionD: "<i>",
    answer: "optionA",
  },
  {
    prompt: "checkbox to'gri yozilgan qatorni toping",
    optionA: "<check>",
    optionB: "<input type='check'>",
    optionC: "<checkbox>",
    optionD: "<input type='checkbox'>",
    answer: "optionD",
  },
  {
    prompt: "Ovozli fayllarni ijro etish uchun qanday teg ishlatiladi?",
    optionA: "<audio>",
    optionB: "<sound>",
    optionC: "<mp3>",
    optionD: "<music>",
    answer: "optionA",
  },
  {
    prompt: "<title> tegining ota-onasi qaysi element hisoblanadi?",
    optionA: "<BODY>",
    optionB: "<TITLE>",
    optionC: "<HTML>",
    optionD: "<HEAD>",
    answer: "optionD",
  },
  {
    prompt: "Inline elementlari har doim yangi satrdan boshlanadimi?",
    optionA: "ha",
    optionB: "yo'q",
    optionC: "bo'lishi mumkin",
    optionD: "ba'zi hollarda",
    answer: "optionB",
  },
  {
    prompt: "HTML-da 'onblur' va 'onfocus' quyidagilar:",
    optionA: "Uslub atributlari",
    optionB: "HTML elementlari",
    optionC: "voqea(hodisa) atributlari",
    optionD: "eshitmaganman",
    answer: "optionC",
  },
  {
    prompt: "Veb-standartlarni kim ishlab chiqaradi?",
    optionA: "Microsoft",
    optionB: "Mozilla",
    optionC: "World Wide Web Consortium (W3C)",
    optionD: "Google",
    answer: "optionC",
  },
  {
    prompt: "Orqa fon rasmini HTML da kiritilgan qatorni belgilang?",
    optionA: "<background img='background.gif'>",
    optionB: "<body bg='background.gif'>",
    optionC: "<body style='background-image:url(background.gif)'>",
    optionD: "<body background-color='red'>",
    answer: "optionC",
  },
  {
    prompt: "Agar rasmni ko'rsatish mumkin bo'lmasa, rasm uchun muqobil matnni qaysi atribut belgilaydi?",
    optionA: "alt",
    optionB: "src",
    optionC: "title",
    optionD: "name",
    answer: "optionA",
  },
  {
    prompt: "Video fayllarni HTML da chiqaradigan tegni belginlang?",
    optionA: "<media>",
    optionB: "<video>",
    optionC: "<movie>",
    optionD: "<cinema>",
    answer: "optionB",
  },
  {
    prompt: "Rasmlar images papkani ichida qismida joylashgan. Page.html faylidan foto.jpg-ga yo'lni qanday to'g'ri yozish mumkin",
    optionA: "images/foto.jpg",
    optionB: "../images/pages/foto.jpg",
    optionC: "pages/images/foto.jpg",
    optionD: "./images/foto.jpg",
    answer: "optionD",
  },
  {
    prompt: "Variantlarning qaysi birida xato mavjud?",
    optionA: "<a href='page.html#17'> Ссылка </a>",
    optionB: "<a href='page.html'> Ссылка </a>",
    optionC: "<a href='page.html#top'> Ссылка </a>",
    optionD: "<a href='page.html'#top> Ссылка </a>",
    answer: "optionD",
  },
  {
    prompt: "Brauzer oynasining o'lchami 1000 piksel. Sahifaga 40% kenglikdagi blok qo'shildi. Keyin ushbu blokga 50% kenglikdagi jadval qo'shildi. Jadvalning pikselli kengligi qancha bo'ladi?",
    optionA: "Ma'lumot etarli emas",
    optionB: " 250 px",
    optionC: "500 px",
    optionD: "200 px",
    answer: "optionC",
  },
  {
    prompt: "Kirish maydonini to'ldirish kerakligini HTMLda qanday atributdan foydalaniladi?",
    optionA: "formvalidate",
    optionB: "validate",
    optionC: " placeholder",
    optionD: "required",
    answer: "optionD",
  },
  {
    prompt: "Sarlavhalar yaratishga imkon beradigan tegni ko'rsating.",
    optionA: "<em>",
    optionB: "<h2>",
    optionC: "<small>",
    optionD: "<strong>",
    answer: "optionB",
  },
  {
    prompt: "Qaysi HTML kod fon rangini qo'shadi?",
    optionA: "<background> yellow </background>",
    optionB: "<body style='background-color:yellow;'>",
    optionC: "<body bg='yellow'>",
    optionD: "hech qaysi to'g'ri emas",
    answer: "optionB",
  },
  {
    prompt: "SVG grafikasi qaysi formatda aniqlangan?",
    optionA: "XML",
    optionB: "HTML",
    optionC: "CSS",
    optionD: "XHTML",
    answer: "optionB",
  },
  {
    prompt: "HTML-da siz SVG elementlarini to'g'ridan-to'g'ri HTML-sahifaga joylashtirishingiz mumkinmi?",
    optionA: "ha",
    optionB: "yo'q",
    optionC: "ba'zi ba'zida",
    optionD: "har doim emas",
    answer: "optionA",
  },
  {
    prompt: "HTML da kommentariya qanday ko'rsatiladi?",
    optionA: "<! - Bu izoh ->",
    optionB: " / * Bu sharh * /",
    optionC: "<? php Bu izohmi?>",
    optionD: "// Bu sharh",
    answer: "optionA",
  },
  {
    prompt: "Matn maydonini yaratish uchun HTML da qaysi tegdan foyadalanamiz?",
    optionA: "<input type='textarea'>",
    optionB: "<textarea>",
    optionC: "<input type='textbox'>",
    optionD: "<textbox>",
    answer: "optionB",
  },
  {
    prompt: "Quyidagi kodda qanday xato bor: <a href='page.html'> <b> <i> 1-sahifa </i> </a>",
    optionA: "<a> tegi uchun talab qilinadigan sarlavha xususiyati yo'q",
    optionB: "<a> tegi ichida <b> tegi va / yoki <i> tegi bo'lishi mumkin emas",
    optionC: "<b> teg yopilmagan",
    optionD: "<a> tegi uchun kerakli alt atributi etishmayapti",
    answer: "optionC",
  },
  
];